//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Royal_Kitchen_Managment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentStock
    {
        public int CurrentStockID { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
